### PR TITLE
Update DeviceInfo spec to 1.1.0

### PR DESCRIPTION
**Pull request by ykulazhenkov**
Add "representor-device" field to support DeviceInfo format 1.1.0.

PR in DeviceInfoSpec repo https://github.com/k8snetworkplumbingwg/device-info-spec/pull/3

### CODE REVIEW

**Comment by ykulazhenkov** [comment]
cc @adrianchiris

**Review by adrianchiris — APPROVED** [review]

**Comment by ykulazhenkov** [comment]
@amorenoz Could you please take a look at this PR?

**Comment by ykulazhenkov** [comment]
> I think a unit test should be added to
> 
> https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/blob/9679314e0bde11898b19f82494b1eff9ae9b075a/pkg/utils/net-attach-def_test.go#L142
> .

I updated spec version in the test and added validation for the new field

**Review by maiqueb — APPROVED** [review]
Thank you.

**Pull request merged**
