### PR TITLE
Fix status annotation name

### LINKED ISSUE #17: Apparent typo in annotation name
**What happend**:

Created some resources using multus and multiple networks. Annotations added to pods did not match spec.

**What you expected to happen**:

According to the spec (https://docs.google.com/document/d/1Ny03h6IDVy_e_vmElOqR7UdTPAG_RNydhVE1Kx54kFQ/)  this should lead to an annotation `k8s.v1.cni.cncf.io/network-status`, but it appeared that the annotation I got was `k8s.v1.cni.cncf.io/networks-status` (note the extra s to make it `networks`, not `network`).

That appears to be a simple typo in the code.

### PR DESCRIPTION
**Pull request by s1061123**
This change fixes #17, mismatching status annotation name between
implementation and specification. During transitional period
(i.e. until next version up), old status annotation is kept for
backward compatibility.

### CODE REVIEW

**Comment by phoracek** [comment]
@s1061123 it failed the CI, could you please look into it? Although I assume it is unrelated.

**Comment by s1061123** [comment]
@phoracek  Sure, let me take a look...

**Comment by s1061123** [comment]
@phoracek updated the diffs (about copyright year) and CI passed.

**Comment by phoracek** [comment]
Interesting... :D Thanks Tomo!

**Pull request merged**
